# Generated by Django 4.0.2 on 2022-02-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogger_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
