# Generated by Django 4.0.2 on 2022-02-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='blogger',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
