# Generated by Django 4.0.2 on 2022-02-16 12:59

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 16, 17, 59, 56, 377304)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(help_text='Enter some text', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Untitled', help_text='Enter the title of the blog', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='description',
            field=models.TextField(help_text='Tell something about yourself', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='first_name',
            field=models.CharField(help_text='Enter your name', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='last_name',
            field=models.CharField(blank=True, help_text='Enter your last name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='nickname',
            field=models.CharField(help_text='Enter your nickname', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 16, 17, 59, 56, 377625)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Add a comment', max_length=1000),
        ),
    ]
